-- 코드를 입력하세요
SELECT date_format(Z.SALES_DATE, '%Y-%m-%d') , Z.PRODUCT_ID , Z.USER_ID , Z.SALES_AMOUNT 
FROM 

(
    SELECT SALES_DATE , PRODUCT_ID , USER_ID , SALES_AMOUNT
    FROM ONLINE_SALE ONS
    

    UNION ALL
    SELECT SALES_DATE , PRODUCT_ID, null , SALES_AMOUNT
    FROM OFFLINE_SALE OFS
   
 ) Z
 WHERE Z.SALES_DATE LIKE '2022-03%'
ORDER BY sales_date asc , PRODUCT_ID asc , USER_ID  asc